# This is a basic workflow to help you get started with Actions

name: Prod Data

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get data prepare code
        uses: actions/checkout@v2

      - name: Get current data version
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.15

      # Runs a single command using the runners shell
      - name: Build data from airtable
        env:
          DATA_PATH: gh-pages
          AIRTABLE_API_KEY: ${{secrets.AIRTABLE_API_KEY}}
          AIRTABLE_BASE: ${{secrets.AIRTABLE_BASE}}
        run: |
          cd backend
          npm i
          npm run import

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: gh-pages/data # The folder the action should deploy
          target-folder: data
