# This is a basic workflow to help you get started with Actions

name: Prod Data

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get data prepare code
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 18.17.1
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"

      - name: Cache Data
        id: cache-data
        uses: actions/cache@v4
        with:
          path: frontend/public/data
          key: lindex-data

      - name: Build 🛠️ data 💾 from airtable
        env:
          DATA_PATH: ./
          AIRTABLE_API_KEY: ${{secrets.AIRTABLE_API_KEY}}
          AIRTABLE_BASE: ${{secrets.AIRTABLE_BASE}}
        run: |
          cd backend
          npm i
          npm run import

      - name: Deploy 🚀 data 💾
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{secrets.FTP_URL}}
          user: ${{secrets.FTP_USERNAME}}
          pass: ${{secrets.FTP_PASSWORD}}
          onlyNewer: false
          restoreMTime: false
          parallel: 2
          localDir: ./frontend/build/data/
          remoteDir: /home/lardepa/lindex/data/
          options: "--delete -p --ignore-time --only-missing"
